### ISSUE TITLE
分p如何正常显示

### ISSUE THREAD

**Issue by zxcasdqwe443** [chen310/BilibiliPotPlayer#1]
有分P的视频只会显示第一P，这个问题怎么解决，附上我观看视频的网址
https://www.bilibili.com/video/BV1Yb411H7G9/?p=1&t=11
![image](https://user-images.githubusercontent.com/45067472/221396479-1da6779e-39c4-469c-b012-e15b5551b308.png)
![image](https://user-images.githubusercontent.com/45067472/221396529-58d62165-c2b3-44d6-aebe-196d9f1a9dc7.png)

**Comment by chen310** [comment]
@zxcasdqwe443 已适配，更新试试

**Comment by zxcasdqwe443** [comment]
> @zxcasdqwe443 已适配，更新试试

没问题了，试了几个多P的都能正常识别播放
