### ISSUE TITLE
medialist类型的合集不能一键导入

### ISSUE THREAD

**Issue by Bel-Air** [chen310/BilibiliPotPlayer#11]

**Comment by chen310** [comment]
来个链接，我适配一下

**Comment by Bel-Air** [comment]
https://space.bilibili.com/26087398/channel/seriesdetail?sid=150096    刚发现这个也不行

**Comment by Bel-Air** [comment]
medialist的话,比如收藏夹,点播放全部,就是了

**Comment by Bel-Air** [comment]
哎不对,播放全部是另一个(虽然也没有一键导入),在点开某个收藏夹后,再点收藏夹名字https://www.bilibili.com/medialist/detail/ml60319735?type=1

**Comment by chen310** [comment]
你给的两个链接都是可以播放的，你是不是没有更新代码？
![ShareX_NhSy9stL6v](https://user-images.githubusercontent.com/33364396/227901438-49c768e2-f2c3-4267-a812-07d350e34d00.png)
![PotPlayerMini64_bgBHqt2njm](https://user-images.githubusercontent.com/33364396/227901550-1e1085d4-f0f9-4328-a5be-db93af74be83.png)

**Comment by Bel-Air** [comment]
具体来说的话,就是up主合集和列表这个页面的导入,收藏夹那个应该无所谓

**Comment by Bel-Air** [comment]
噢噢,感谢,好快(
