### ISSUE TITLE
原视频1080p但是到了potplayer上只有360p

### ISSUE THREAD

**Issue by Xtscat** [chen310/BilibiliPotPlayer#14]
视频地址如下：https://www.bilibili.com/video/BV1Zr4y157Xz/?spm_id_from=333.788.recommend_more_video.1&vd_source=9b68089432871c0c66ff7f285fafe582

![image](https://user-images.githubusercontent.com/56481656/228997887-4c1f130e-19ff-41ae-918f-0435ddc93d6c.png)

![image](https://user-images.githubusercontent.com/56481656/228997853-7f78f45f-8328-4116-bad2-0de6551f83fd.png)

**Comment by chen310** [comment]
你没登录
![explorer_d6gvfxHgXZ](https://user-images.githubusercontent.com/33364396/228998896-92db89a3-368d-432c-beb6-bd46463a5f26.png)
