### ISSUE TITLE
复制视频的地址在potplayer播放时没有声音，且画面很小，分辨率低。放直播的就没问题

### ISSUE THREAD

**Issue by hougal** [chen310/BilibiliPotPlayer#25]
![image_6](https://user-images.githubusercontent.com/86551009/235159627-91a656f2-440b-4866-be22-9325e6cceebb.png)

**Comment by zhaoxin-wen** [comment]
同样碰到这种情况，估计是cookie没有设置成功。但是我填写cookie后，点击测试，提示“无法运作。”
不理解设置了cookie为什么不行。

**Comment by TonyK922** [comment]
我也是, 更新到最新版. 没有声音，分辨率低

**Comment by chen310** [comment]
右下角切换一下清晰度试试

**Comment by gensokyoukiyoe** [comment]
我初次设置也是没声音，后来按照楼上说的修改清晰度就出声了。👍

**Comment by hougal** [comment]
修改清晰度后就好了
