### ISSUE TITLE
一些网址不能解析了

### ISSUE THREAD

**Issue by GithubUsername3** [chen310/BilibiliPotPlayer#28]
感谢提供这么好的工具，不过最近有些问题出现。

自带的搜索功能的链接不能解析
https://search.bilibili.com/video?keyword=陈奕迅

以space为前缀的多位up主个人空间所有作品的链接不能解析，前几天还正常，比如
https://space.bilibili.com/417567377

付费大会员的链接不能解析，免费会员或未登录使得完整视频不能解析还算正常，但免费的前6分钟应该能解析才对
https://www.bilibili.com/bangumi/play/ss39188

**Comment by chen310** [comment]
@GithubUsername3 
1. 搜索我这里测试是可以使用的
2. 已修复，更新代码即可
3. 这个没有仔细研究过，免费6分钟应该也用处不大吧

**Comment by WuJunkai2004** [comment]
依然无法进行搜索
提示如下
![屏幕截图 2023-06-11 182440](https://github.com/chen310/BilibiliPotPlayer/assets/50454344/aaf7a23c-8913-49f2-91f9-7861854cb190)
