### ISSUE TITLE
建议写上怎么获取cookies

### ISSUE THREAD

**Issue by kdXiaoyi** [chen310/BilibiliPotPlayer#3]
对于部分小白，使用这个软件可能会有写困难
~~从不好的角度看，不写cookies获取方法可能被骂（最好别发生）~~

等下发个PR来帮作者大大加个人找到的办法

# 《应该能用的方案》
参阅：https://github.com/XiaoMiku01/bili-live-heart/blob/master/doc_old/bili.md
# 《应该**不能**用的方案》
从隔壁项目薅过来的JS：
```js
javascript: (() => {
    if (location.host.includes('www.bilibili.com')) {
        var cookie = document.cookie;
        navigator.clipboard.writeText(cookie);
        alert('Cookie 已复制到剪贴板');
    } else {
        alert('当前网页不为BILIBILI页面');
    }
})();
```

MD里面插下面的代码就可以插一个链接，拖到标题栏就可以创建书签
bilibili点书签就自动复制书签
```html
<a href="javascript:(()=>{if(location.host.includes('www.bilibili.com')){var cookie=document.cookie;navigator.clipboard.writeText(cookie);alert('Cookie 已复制到剪贴板')}else{alert('当前网页不为BILIBILI页面')}})();">获取B站 Cookie</a>
```
## 测试
经edge 110 on win11测试，可复制到：
```cookies
buvid3=82**屏蔽**E73EFFE
```

但是复制到potplayer里面提示不可用
![image](https://user-images.githubusercontent.com/96934144/221422720-3664c59e-6b41-4b5b-9363-539178cf2e16.png)

建议作者适配

**Comment by chen310** [comment]
第二种获取的cookie没法用

**Comment by kdXiaoyi** [comment]
第二个的JS是从[xunkong](https://github.com/xunkong/xunkong/)薅过来的
原设计用于miyoushe.com的账号cookies获取，且能正常使用
