### ISSUE TITLE
看不了番剧

### ISSUE THREAD

**Issue by 398946584** [chen310/BilibiliPotPlayer#31]
我是大会员 但是不论是会员番剧还是普通番剧 都看不了 potplayer也更新到最新 插件的新旧版本都试过了 但是都是提示服务器已关闭或地址错误，而视频可以正常播放 求解决
![image](https://github.com/chen310/BilibiliPotPlayer/assets/96293709/615b34f4-7175-4b2e-9d56-7f592ccf41ed)

**Comment by chen310** [comment]
我这里是没问题的

**Comment by 398946584** [comment]
> 我这里是没问题的

好的，感谢 现在已经好了 请问什么时候更新一下不能看b站分p分集的视频？现在这类视频只能看第一集或者P1

**Comment by chen310** [comment]
分p不是一直都可以吗

**Comment by 398946584** [comment]
实际上分P只能看到第一个 比如在稍后观看里 我在点开视频前可以在ppt播放列表里看到完整的播放时间
![image](https://github.com/chen310/BilibiliPotPlayer/assets/96293709/f23dec77-1ad1-4d69-878c-b3307ceff7dc)
但是点击播放之后就只有1p的播放时间了无法播放后面的视频
![image](https://github.com/chen310/BilibiliPotPlayer/assets/96293709/265396a3-2630-43c3-8543-8900e593b7e0)

**Comment by chen310** [comment]
像稍后观看和历史记录这种列表中的视频都只能看p1，要看完整的分集要单独打开链接

**Comment by 398946584** [comment]
收到 已解决 感谢
