### ISSUE TITLE
番剧只能看第一集

### ISSUE THREAD

**Issue by GoblinCwl** [chen310/BilibiliPotPlayer#33]
【游☆戏☆王 5D's 第一季：第2话 力量型昆虫卡组！蚁地狱的陷阱】 https://www.bilibili.com/bangumi/play/ep30960/?share_source=copy_web

不管点哪一集，播放的都是第一集的内容
![1](https://github.com/chen310/BilibiliPotPlayer/assets/40445489/9f9e5f17-2d0f-4b65-aa02-107a0236da5a)

**Comment by GoblinCwl** [comment]
我发现只有这部番剧出现这个问题，其他番剧可以正常看

**Comment by chen310** [comment]
@GoblinCwl 已修复，更新试试
