### ISSUE TITLE
设置了cookie后不能播放

### ISSUE THREAD

**Issue by shensl4499** [chen310/BilibiliPotPlayer#5]
请问遇到了这种情况怎么解决，不设置cookie的时候，ctrl+u可以播放，设置了cookie就不能播放了
![image](https://user-images.githubusercontent.com/41412753/221744466-094d9f6a-24af-4573-a102-2ebf609d02af.png)

**Comment by chen310** [comment]
设置cookie后，点测试有显示账号信息吗

**Comment by shensl4499** [comment]
显示账号信息了

**Comment by shensl4499** [comment]
> 

显示账号信息了

**Comment by chen310** [comment]
potplayer什么版本，升级试试

**Comment by shensl4499** [comment]
> potplayer什么版本，升级试试

一直在最新版本下做的测试
![image](https://user-images.githubusercontent.com/41412753/221758095-e80ec0b1-8086-42ab-a439-d36d4dae738d.png)

**Comment by chen310** [comment]
到代码文件中把debug=false改为debug=true，看看设置cookie和不设置cookie有什么不同

**Comment by shensl4499** [comment]
> 到代码文件中把debug=false改为debug=true，看看设置cookie和不设置cookie有什么不同

![image](https://user-images.githubusercontent.com/41412753/221760532-da7f02fb-b873-42ae-ab6b-017346359a4e.png)

**Comment by chen310** [comment]
不设置cookie呢，把cookie删了，重启试试

**Comment by shensl4499** [comment]
> 不设置cookie呢，把cookie删了，重启试试

![image](https://user-images.githubusercontent.com/41412753/221761179-87a7f084-4d23-4798-9a6c-e4c1ea475a3a.png)

**Comment by chen310** [comment]
https://github.com/chen310/BilibiliPotPlayer/blob/master/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L154-L163 这里改一下试试
```AngelScript
string post(string url, string data="") {
	string UserAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36";
	string Headers = "Referer: https://www.bilibili.com\r\n";
	Headers += "User-Agent: " + UserAgent + "\r\n";
	if (!cookie.empty()) {
		Headers += "Cookie: " + cookie + "\r\n";
	}
	log("request", url);
	string res = HostUrlGetStringWithAPI(url, UserAgent, Headers, data, true);
	res = HostDecompress(res);
	log("res", res);
	return res;
}
```

**Comment by shensl4499** [comment]
> https://github.com/chen310/BilibiliPotPlayer/blob/master/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L154-L163 这里改一下试试
> 
> ```angelscript
> string post(string url, string data="") {
> 	string UserAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36";
> 	string Headers = "Referer: https://www.bilibili.com\r\n";
> 	Headers += "User-Agent: " + UserAgent + "\r\n";
> 	if (!cookie.empty()) {
> 		Headers += "Cookie: " + cookie + "\r\n";
> 	}
> 	log("request", url);
> 	string res = HostUrlGetStringWithAPI(url, UserAgent, Headers, data, true);
> 	res = HostDecompress(res);
> 	log("res", res);
> 	return res;
> }
> ```

request: https://api.bilibili.com/x/player/playurl?avid=309952238&cid=1025138333&qn=120&fnval=128&fourk=1
res: {"code":-412,"message":"请求被拦截","ttl":1,"data":null}

**Comment by chen310** [comment]
不清楚，是不是触发风控了

**Comment by shensl4499** [comment]
> 不清楚，是不是触发风控了

https://api.bilibili.com/x/player/playurl?avid=309952238&cid=1025138333&qn=120&fnval=128&fourk=1
复制这个地址，在浏览器地址栏粘贴、回车，可以看到数据正常返回，
![image](https://user-images.githubusercontent.com/41412753/221765607-466e41d2-c79a-4d60-9f5d-504573385c18.png)
从github的issue里，直接点击这个地址就报错了，
![image](https://user-images.githubusercontent.com/41412753/221766133-ee52ef70-8f0a-44de-9e0a-b48015cb882c.png)
难道是bili校验referer了？

**Comment by chen310** [comment]
我设置referer了。你重新登录获取新的cookie试试？

**Comment by shensl4499** [comment]
> 我设置referer了。你重新登录获取新的cookie试试？

post里，我把cookie赋值，由SESSDATA改成直接用full_cookie，现在可以正常播放列表了。感谢开发。
L114
//cookie = cookies[i].substr(pos);
cookie = full_cookie;

**Comment by chen310** [comment]
OK，那等会儿我改一下

**Comment by shensl4499** [comment]
然后还原回去，也验证了一下。直接使用cookie=SESSDATA，确实又不能播放列表，再换成cookie=full_cookie，又可以播放了
