### ISSUE TITLE
打开链接报错

### ISSUE THREAD

**Issue by YokiiroBW** [chen310/BilibiliPotPlayer#51]
不管是从Bzhan站主页或者是播放列表打开，加载后弹出这个报错。请问是什么原因
电脑为5800X+6750XT

![image](https://github.com/chen310/BilibiliPotPlayer/assets/82425598/4e33028e-9840-4810-8b5e-aecca2b409a6)

**Comment by chen310** [comment]
不清楚，重启或者重装软件试试？

**Comment by YokiiroBW** [comment]
更新显卡驱动后好了，这个就很奇怪。
