### ISSUE TITLE
弹幕的调整

### ISSUE THREAD

**Issue by Xrjang** [chen310/BilibiliPotPlayer#52]
我研究了好久，没找到修改弹幕的选项，我希望添加这项功能，这样PotPlayer就是真正的b站客户端了

**Comment by chen310** [comment]
改[这一行](https://github.com/chen310/BilibiliPotPlayer/blob/master/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L31)

**Comment by ai-y-f** [comment]
右键之后点击字幕，把显示字幕点掉就行

**Comment by ai-y-f** [comment]
alt+h可以开关弹幕，不知道你说的是不是这个，不过貌似确实不能发弹幕

**Comment by Xrjang** [comment]
> alt+h可以开关弹幕，不知道你说的是不是这个，不过貌似确实不能发弹幕

我是想说弹幕大小和可显示区域等调节的

**Comment by fdy96** [comment]
> 改[这一行](https://github.com/chen310/BilibiliPotPlayer/blob/master/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L31)

font_size=30.0参数名不对，应该是fontsize=30.0

**Comment by chen310** [comment]
> > 改[这一行](https://github.com/chen310/BilibiliPotPlayer/blob/master/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L31)
> 
> font_size=30.0参数名不对，应该是fontsize=30.0

好的，改过来了，现在应该是 font_size
