### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by IchTanze** [chen310/BilibiliPotPlayer#54]
您好，使用potplayer打开B站搜索网址时，如果输入的关键字是中文，就会打不开该网址；如果将中文进行URL编码之后又可以打开。请问有什么好的办法解决这个问题吗

**Comment by chen310** [comment]
不知道是不是和potplayer版本有关，我这里使用中文，好像会自动编码

**Comment by IchTanze** [comment]
解决了，我刚刚测试的时候选中 打开链接 界面的 同时打开字幕 选项就加载成功了。

**Comment by simonxiao86** [comment]
[		kw = parse(path, "keyword");](https://github.com/chen310/BilibiliPotPlayer/blob/b9ba636b42eddcf84cbee3885edcb7c7d5acd715/Media/PlayParse/MediaPlayParse%20-%20Bilibili.as#L1304)
这一行改成 `kw = HostUrlEncode(parse(path, "keyword"));` ，我这边就能正确解析中文，不需要先进行 url 编码了
