### ISSUE TITLE
直播无法观看，不知道是什么原因

### ISSUE THREAD

**Issue by devilmandare** [chen310/BilibiliPotPlayer#56]
直接输入直播间号，无法播放，是不是还得去抓什么别的链接才能播放？

**Comment by chen310** [comment]
需要使用直播间的链接

**Comment by huajiba** [comment]
需要完整的直播间地址`live.bilibili.com/房间号`。打开直播间直接复制url地址就行了，单独的房间号是不行的哈。应该可以关闭issues了。
