### ISSUE TITLE
大佬,能否把在线弹幕给拉到本地

### ISSUE THREAD

**Issue by na-nali** [chen310/BilibiliPotPlayer#64]
阿b的一些番剧会删减,所以经常下好无删减版本的观看,但是没有弹幕又少了点味道,来询问下有没有什么操作能把弹幕保存到本地

**Comment by chen310** [comment]
下载弹幕有许多工具，比如 [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved)
