### ISSUE TITLE
“投稿”中视频列表部分解析错误

### ISSUE THREAD

**Issue by pascalqq** [chen310/BilibiliPotPlayer#69]
不知道是否是视频数量的问题，当使用
https://space.bilibili.com/364219029/video
时，解析正常
![image](https://github.com/chen310/BilibiliPotPlayer/assets/2882959/8fd07db0-63fa-41d9-a101-c14e1b8b2ddc)

当尝试使用
https://space.bilibili.com/343348/video
时，解析报错
![image](https://github.com/chen310/BilibiliPotPlayer/assets/2882959/2f14d34e-9e37-4a6c-b5a0-9c9788e0b8fd)

麻烦看看是啥问题，能修复不😘

**Comment by pascalqq** [comment]
顺便夸一下这个插件很有用，当我的一些老设备能够硬解B站视频，风扇不用再呼呼呼了。

**Comment by chen310** [comment]
确实是视频数量太多引起的。视频数量多，导致需要请求很多次，导致超时。我加了次数限制，你更新试试

**Comment by pascalqq** [comment]
感谢，亲测已fix
