### ISSUE TITLE
希望加上更多的清晰度和视频编码选择

### ISSUE THREAD

**Issue by hpmdr** [chen310/BilibiliPotPlayer#7]
感谢作者，我的弱鸡电脑有救了，b站网页看视频风扇狂转，续航尿崩。potplayer用这个插件硬解b站视频简直无敌。
但是我发现清晰度选项只有1080P和360P，视频编码也默认是AVC。我用的4G路由器上网希望省点流量。
所以希望作者加上更多的清晰度和视频编码选择。

**Comment by hpmdr** [comment]
视频网站的视频一般是分段加载的，是不是AVC就是完整视频。每次播放视频的时候都会缓存整个视频。

**Comment by chen310** [comment]
dash有所有的清晰度，但是视频和音频是分离的，暂时没有办法播放

**Comment by hpmdr** [comment]
感谢支持，作者牛逼
